export const STORAGE_CONSTANTS = {
  TOKEN: '@TOKEN',
  CONFIGURATIONS: '@CONFIGURATIONS',
  IS_ALREADY_LAUNCHED: '@IS_ALREADY_LAUNCHED',
  NAVIGATION_STATE: 'NAVIGATION_STATE',
  NOTIFICATION_PERMISSION: 'NOTIFICATION_PERMISSION', // 'denied' | 'granted'
}

export type StorageKey = keyof typeof STORAGE_CONSTANTS
